# Generated by Django 6.0.4 on 2026-05-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('commercial', 'Commercial'), ('music_video', 'Music Video'), ('cinematic', 'Cinematic'), ('reels', 'Reels'), ('corporate', 'Corporate'), ('documentary', 'Documentary')], default='cinematic', max_length=30)),
                ('embed_url', models.URLField(help_text='YouTube or Vimeo embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail image URL')),
                ('duration', models.CharField(blank=True, help_text='e.g. 2:34', max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='videos.tag')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
