# Generated by Django 6.0.4 on 2026-05-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_file',
            field=models.ImageField(blank=True, help_text='Upload a local thumbnail image', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a local video file (.mp4, .webm, etc.)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo embed URL (alternative to uploading a video file)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL (alternative to uploading a thumbnail file)'),
        ),
    ]
