# Generated by Django 6.0.4 on 2026-05-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('project_type', models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('music_video', 'Music Video'), ('corporate', 'Corporate'), ('documentary', 'Documentary'), ('reels', 'Social Media Reels'), ('other', 'Other')], max_length=30)),
                ('budget_range', models.CharField(blank=True, choices=[('under_500', 'Under ₹500'), ('500_1000', '₹500 – ₹1,000'), ('1000_3000', '₹1,000 – ₹3,000'), ('3000_plus', '₹3,000+'), ('discuss', "Let's Discuss")], max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
