# Generated by Django 6.0.4 on 2026-06-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('under_5k', 'Under ₹5,000'), ('5k_15k', '₹5,000 – ₹15,000'), ('15k_50k', '₹15,000 – ₹50,000'), ('50k_plus', '₹50,000+'), ('discuss', "Let's Discuss")], max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='project_type',
            field=models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('music_video', 'Music Video'), ('corporate', 'Corporate'), ('documentary', 'Documentary'), ('reels', 'Social Media Reels'), ('wedding', 'Wedding Film'), ('other', 'Other')], max_length=30),
        ),
    ]
